"""initial schema

Revision ID: 22721dfd9b56
Revises: 
Create Date: 2026-10-02 10:16:23.871800
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '22721dfd9b56'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    op.create_table('notes',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.Enum('command', 'sql', 'text', 'config', 'code', name='note_kind', native_enum=False, length=32), server_default='command', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_dangerous', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('manual', 'obsidian', 'github', 'agent', name='note_source', native_enum=False, length=32), server_default='manual', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(content)) > 0', name=op.f('ck_notes_content_not_blank')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_notes_title_not_blank')),
    sa.CheckConstraint('use_count >= 0', name=op.f('ck_notes_use_count_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notes_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('ix_notes_deleted_at', 'notes', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index(op.f('ix_notes_kind'), 'notes', ['kind'], unique=False)
    op.create_index('ix_notes_pinned_recent', 'notes', ['is_pinned', 'updated_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.create_index(op.f('ix_notes_source'), 'notes', ['source'], unique=False)
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('uq_notes_source_external_id', 'notes', ['source', 'external_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('tasks',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('backlog', 'todo', 'in_progress', 'blocked', 'done', 'cancelled', name='task_status', native_enum=False, length=32), server_default='todo', nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='task_priority', native_enum=False, length=32), server_default='medium', nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('estimate_minutes', sa.Integer(), nullable=True),
    sa.Column('spent_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False),
    sa.Column('source', sa.Enum('manual', 'jira', 'calendar', 'email', 'obsidian', 'github', 'gitlab', 'agent', name='task_source', native_enum=False, length=32), server_default='manual', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('estimate_minutes IS NULL OR estimate_minutes > 0', name=op.f('ck_tasks_estimate_minutes_positive')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_tasks_title_not_blank')),
    sa.CheckConstraint('spent_minutes >= 0', name=op.f('ck_tasks_spent_minutes_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_deleted_at', 'tasks', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index('ix_tasks_open_agenda', 'tasks', ['scheduled_for', 'due_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_scheduled_for'), 'tasks', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_tasks_source'), 'tasks', ['source'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_tags', 'tasks', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('uq_tasks_source_external_id', 'tasks', ['source', 'external_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('task_events',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'updated', 'status_changed', 'scheduled', 'time_logged', 'completed', 'reopened', 'note_added', 'synced', 'deleted', 'restored', name='task_event_type', native_enum=False, length=32), nullable=False),
    sa.Column('actor', sa.String(length=100), server_default='user', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_events_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_events'))
    )
    op.create_index('ix_task_events_task_created', 'task_events', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_events_task_id'), 'task_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_events_task_id'), table_name='task_events')
    op.drop_index('ix_task_events_task_created', table_name='task_events')
    op.drop_table('task_events')
    op.drop_index('uq_tasks_source_external_id', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_tasks_tags', table_name='tasks', postgresql_using='gin')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduled_for'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index('ix_tasks_open_agenda', table_name='tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index('ix_tasks_deleted_at', table_name='tasks', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('tasks')
    op.drop_index('uq_notes_source_external_id', table_name='notes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_index(op.f('ix_notes_source'), table_name='notes')
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.drop_index('ix_notes_pinned_recent', table_name='notes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_notes_kind'), table_name='notes')
    op.drop_index('ix_notes_deleted_at', table_name='notes', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('notes')
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
